import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Types for the autotable plugin which isn't always picked up by TS
import { UserOptions } from 'jspdf-autotable';

interface jsPDFWithPlugin extends jsPDF {
    autoTable: (options: UserOptions) => jsPDF;
}

export const PDF_COLORS = {
    PRIMARY: [128, 0, 32] as [number, number, number], // #800020 Burgundy
    SECONDARY: [75, 85, 99] as [number, number, number], // #4b5563 Gray
    TEXT_DARK: [26, 26, 46] as [number, number, number], // #1a1a2e
    TEXT_MUTED: [107, 114, 128] as [number, number, number], // #6b7280
    DIVIDER: [229, 231, 235] as [number, number, number], // #e5e7eb
    STRIPE: [255, 249, 250] as [number, number, number], // #FFF9FA
};

/**
 * Fetches an image from a URL and converts it to a Base64 string for jsPDF
 */
export async function getBase64Image(url: string): Promise<string> {
    try {
        if (url.startsWith('data:image')) return url;
        
        const response = await fetch(url);
        const blob = await response.blob();
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
    } catch (error) {
        console.error('Failed to convert image to base64:', error);
        return '';
    }
}

/**
 * Draws the standard institutional header used across all reports
 */
export async function drawHeader(
    doc: jsPDF,
    schoolName: string,
    reportTitle: string,
    logoUrl: string,
    metadata?: string[]
) {
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Add Logo
    if (logoUrl) {
        try {
            const logoBase64 = await getBase64Image(logoUrl);
            if (logoBase64) {
                // Approximate 110x110 size from current React-PDF template
                // React-PDF uses points/pixels, jsPDF uses mm by default. 
                // 110px is roughly 29mm at 72dpi, but let's use a balanced size.
                doc.addImage(logoBase64, 'PNG', 15, 15, 30, 30);
            }
        } catch (e) {
            console.warn('Could not add logo to PDF:', e);
        }
    }

    // School Name
    doc.setTextColor(PDF_COLORS.TEXT_DARK[0], PDF_COLORS.TEXT_DARK[1], PDF_COLORS.TEXT_DARK[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text(schoolName.toUpperCase(), 50, 25);

    // Report Title
    doc.setTextColor(PDF_COLORS.SECONDARY[0], PDF_COLORS.SECONDARY[1], PDF_COLORS.SECONDARY[2]);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(13);
    doc.text(reportTitle, 50, 32);

    // Metadata (Generated date, User, etc.)
    if (metadata && metadata.length > 0) {
        doc.setTextColor(PDF_COLORS.TEXT_MUTED[0], PDF_COLORS.TEXT_MUTED[1], PDF_COLORS.TEXT_MUTED[2]);
        doc.setFontSize(9);
        metadata.forEach((text, index) => {
            doc.text(text, 50, 38 + (index * 4.5));
        });
    }

    // Horizontal Divider
    doc.setDrawColor(PDF_COLORS.DIVIDER[0], PDF_COLORS.DIVIDER[1], PDF_COLORS.DIVIDER[2]);
    doc.line(15, 55, pageWidth - 15, 55);
}

/**
 * Draws the standard footer and watermark
 */
export function drawFooter(
    doc: jsPDF,
    schoolName: string,
    userEmail: string
) {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const timestamp = new Date().toISOString();
    
    // Page Number
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        
        // Footer text
        doc.setTextColor(156, 163, 175); // #9ca3af
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        
        const footerText = `This is a system-generated report from ${schoolName}. Confidential.`;
        doc.text(footerText, pageWidth / 2, pageHeight - 15, { align: 'center' });
        
        const watermarkText = `Generated by ${schoolName} • Exported by ${userEmail} • ${timestamp}`;
        doc.text(watermarkText, pageWidth / 2, pageHeight - 10, { align: 'center' });
        
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
    }
}

/**
 * Creates a standard autotable configuration with branding and design consistency
 */
export function getBaseTableOptions(doc: jsPDF, schoolName: string, userEmail: string): UserOptions {
    return {
        theme: 'striped',
        headStyles: {
            fillColor: PDF_COLORS.PRIMARY,
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'left'
        },
        bodyStyles: {
            fontSize: 9,
            textColor: [55, 65, 81],
        },
        alternateRowStyles: {
            fillColor: PDF_COLORS.STRIPE
        },
        margin: { left: 15, right: 15, top: 20, bottom: 25 },
        didDrawPage: (data) => {
            // Draw watermark/footer on every page
            const pageHeight = doc.internal.pageSize.getHeight();
            const pageWidth = doc.internal.pageSize.getWidth();
            const timestamp = new Date().toISOString();
            
            doc.setTextColor(156, 163, 175);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            
            const watermarkText = `Generated by ${schoolName} • Exported by ${userEmail} • ${timestamp}`;
            doc.text(watermarkText, pageWidth / 2, pageHeight - 10, { align: 'center' });
        }
    };
}
